# Generated by Django 5.1 on 2024-09-02 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Helmet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=4)),
                ('description', models.TextField(max_length=250)),
            ],
        ),
    ]
