# Generated by Django 5.1 on 2024-09-02 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_helmet_description_alter_helmet_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand', models.CharField(choices=[('BELL', 'BELL'), ('Arai', 'Arai'), ('Shoei', 'Shoei')], default='BELL', max_length=10)),
                ('helmet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.helmet')),
            ],
        ),
    ]
