# Generated by Django 5.1 on 2024-09-03 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='Brand',
            new_name='brand',
        ),
        migrations.AlterField(
            model_name='brand',
            name='helmet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='main_app.helmet'),
        ),
    ]
